{
 "title": "Panel Entradas Analógicas",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Taller Instrumentos PRIII",
   "type": "text",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "# 🧪 Panel Entradas Analógicas\n\n**Taller:** Instrumentos PRIII  \n**Canal:** `AI.0` `AI.2` `AI.3`  \n⏰ _Rango de visualización:_ ${__from:date:DD-MM-YYYY HH\\:mm\\:ss} al ${__to:date:DD-MM-YYYY HH\\:mm\\:ss}\n\n"
   }
  },
  {
   "title": "Patrón manométrico",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bar g" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "bar g",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AI_PV_DATA",
     "query": "from(bucket: \"plc_data_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AI00PV\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group()",
     "select": [
      [
       { "params": [ "ai_00pv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Patrón absoluto",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbar  a" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "mbar a",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AI_PV_DATA",
     "query": "from(bucket: \"plc_data_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ai_01pv\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group()\r\n",
     "select": [
      [
       { "params": [ "ai_01pv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PANEL ENTRADA ANALOGICA 3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Valor instantaneo AI",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "pv",
       "measurement": "AI_PV_DATA",
       "query": "SELECT last(\"ai_02pv\") FROM \"AI02_DATA\" WHERE $timeFilter SLIMIT 1",
       "select": [
        [
         { "params": [ "ai_02pv" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "unit",
       "query": "SELECT last(\"ai_02unit\") AS \"unit\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI02'"
      },
      {
       "alias": "lrv",
       "query": "SELECT last(\"ai_02lrv\") AS \"lrv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI02'"
      },
      {
       "alias": "urv",
       "query": "SELECT last(\"ai_02urv\") AS \"urv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI02'"
      }
     ]
    },
    {
     "title": "Tendencia AI",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 14, "x": 10, "y": 6 },
     "targets": [
      {
       "alias": "ai_pv_trend",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "AI_PV_DATA",
       "select": [
        [
         { "params": [ "ai_02pv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "lrv",
       "query": "SELECT last(\"ai_02lrv\") AS \"lrv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI02'"
      },
      {
       "alias": "urv",
       "query": "SELECT last(\"ai_02urv\") AS \"urv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI02'"
      },
      {
       "alias": "unit",
       "query": "SELECT last(\"ai_02unit\") AS \"unit\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI02'"
      }
     ]
    },
    { "title": "AI 3 Configuración LRV y URV", "type": "volkovlabs-form-panel", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 54 } },
    {
     "title": "Rango actual",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "LRV",
       "query": "SELECT last(\"ai_02lrv\") AS \"lrv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI02'"
      },
      {
       "alias": "URV",
       "query": "SELECT last(\"ai_02urv\") AS \"urv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI02'"
      }
     ]
    }
   ]
  },
  {
   "title": "PANEL ENTRADA ANALOGICA 4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Valor instantaneo AI",
     "type": "gauge",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "pv",
       "measurement": "AI_PV_DATA",
       "query": "SELECT last(\"ai_02pv\") FROM \"AI02_DATA\" WHERE $timeFilter SLIMIT 1",
       "select": [
        [
         { "params": [ "ai_03pv" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {
       "alias": "unit",
       "query": "SELECT last(\"ai_03unit\") AS \"unit\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI03'"
      },
      {
       "alias": "lrv",
       "query": "SELECT last(\"ai_03lrv\") AS \"lrv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI03'"
      },
      {
       "alias": "urv",
       "query": "SELECT last(\"ai_03urv\") AS \"urv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI03'"
      }
     ]
    },
    {
     "title": "Tendencia AI",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 14, "x": 10, "y": 7 },
     "targets": [
      {
       "alias": "ai_pv_trend",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "AI_PV_DATA",
       "select": [
        [
         { "params": [ "ai_03pv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "lrv",
       "query": "SELECT last(\"ai_03lrv\") AS \"lrv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI03'"
      },
      {
       "alias": "urv",
       "query": "SELECT last(\"ai_03urv\") AS \"urv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI03'"
      },
      {
       "alias": "unit",
       "query": "SELECT last(\"ai_03unit\") AS \"unit\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI03'"
      }
     ]
    },
    { "title": "AI 4 Configuración LRV y URV", "type": "volkovlabs-form-panel", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 19 } },
    {
     "title": "Rango actual",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "LRV",
       "query": "SELECT last(\"ai_03lrv\") AS \"lrv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI03'"
      },
      {
       "alias": "URV",
       "query": "SELECT last(\"ai_03urv\") AS \"urv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI03'"
      }
     ]
    }
   ]
  },
  {
   "title": "PANEL ENTRADA ANALÓGICA 5 - PASIVA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Valor instantaneo AI",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "pv",
     "measurement": "AI_PV_DATA",
     "query": "SELECT last(\"ai_02pv\") FROM \"AI02_DATA\" WHERE $timeFilter SLIMIT 1",
     "select": [
      [
       { "params": [ "ai_04pv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "unit",
     "query": "SELECT last(\"ai_04unit\") AS \"unit\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI04'"
    },
    {
     "alias": "lrv",
     "query": "SELECT last(\"ai_04lrv\") AS \"lrv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI04'"
    },
    {
     "alias": "urv",
     "query": "SELECT last(\"ai_04urv\") AS \"urv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI04'"
    }
   ]
  },
  {
   "title": "Tendencia AI",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "alias": "ai_pv_trend",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AI_PV_DATA",
     "select": [
      [
       { "params": [ "ai_04pv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "lrv",
     "query": "SELECT last(\"ai_04lrv\") AS \"lrv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI04'"
    },
    {
     "alias": "urv",
     "query": "SELECT last(\"ai_04urv\") AS \"urv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI04'"
    },
    {
     "alias": "unit",
     "query": "SELECT last(\"ai_04unit\") AS \"unit\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI04'"
    }
   ]
  },
  { "title": "AI 5 Configuración LRV y URV", "type": "volkovlabs-form-panel", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 } },
  {
   "title": "Rango actual",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "LRV",
     "query": "SELECT last(\"ai_04lrv\") AS \"lrv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI04'"
    },
    {
     "alias": "URV",
     "query": "SELECT last(\"ai_04urv\") AS \"urv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI04'"
    }
   ]
  }
 ]
}