{
 "title": "Panel Salidas Analógicas",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Taller Instrumentos PRIII",
   "type": "text",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "# 🧪 Panel Salida Analógica\n\n**Canales:** `AO00` `AO01` `AI02` `AI03` `DI00` `DI01` `DI02` `DI03` `DO00` `DO01` `DO02` `DO03`\n"
   }
  },
  {
   "title": "Patrón manométrico",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bar g" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "bar g",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AI_PV_DATA",
     "query": "from(bucket: \"plc_data_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AI00PV\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group()",
     "select": [
      [
       { "params": [ "ai_00pv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Patrón absoluto",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbar  a" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "mbar a",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AI_PV_DATA",
     "query": "from(bucket: \"plc_data_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ai_01pv\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group()\r\n",
     "select": [
      [
       { "params": [ "ai_01pv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Entradas digitales",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DI 01",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"di00_input\") FROM \"DI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DI00'\n",
     "select": [
      [
       { "params": [ "di00_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI00" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "30d" }
     ]
    },
    {
     "alias": "DI 02",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"di01_input\") FROM \"DI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DI01'",
     "select": [
      [
       { "params": [ "di01_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI01" }
     ]
    },
    {
     "alias": "DI 03",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"di02_input\") FROM \"DI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DI02'",
     "select": [
      [
       { "params": [ "di02_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI02" }
     ]
    },
    {
     "alias": "DI 04",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"di03_input\") FROM \"DI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DI03'",
     "select": [
      [
       { "params": [ "di03_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI03" }
     ]
    }
   ]
  },
  { "title": "Activar DO's", "type": "volkovlabs-form-panel", "gridPos": { "h": 7, "w": 3, "x": 12, "y": 4 } },
  {
   "title": "Estado de las salidas digitales",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DO 01",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"DO00_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO00'\n",
     "select": [
      [
       { "params": [ "di00_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI00" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "30d" }
     ]
    },
    {
     "alias": "DO 02",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"DO01_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO01'",
     "select": [
      [
       { "params": [ "di01_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI01" }
     ]
    },
    {
     "alias": "DO 03",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"DO02_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO02'",
     "select": [
      [
       { "params": [ "di02_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI02" }
     ]
    },
    {
     "alias": "DO 04",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"DO03_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO03'",
     "select": [
      [
       { "params": [ "di03_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI03" }
     ]
    }
   ]
  },
  { "title": "OUT AO 1 - 4 a 20 mA", "type": "volkovlabs-form-panel", "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 } },
  {
   "title": "Salidas analogicas y retornos de posición",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "AI02_CONFIG",
     "query": "SELECT last(\"ao_00out\") AS \"OUT 1\" FROM \"AO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AO00'\n\n",
     "select": [
      [
       { "params": [ "ai_02lrv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ai_02urv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "measurement": "AI02_CONFIG",
     "query": "SELECT last(\"ao_01out\") AS \"OUT 2\" FROM \"AO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AO01'\n\n",
     "select": [
      [
       { "params": [ "ai_02lrv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ai_02urv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "measurement": "AI02_CONFIG",
     "query": "SELECT last(\"ai_02pv\") AS \"FEED 1\" FROM \"AI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI02_FEED'\n\n",
     "select": [
      [
       { "params": [ "ai_02lrv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ai_02urv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "measurement": "AI02_CONFIG",
     "query": "SELECT last(\"ai_03pv\") AS \"FEED 2\" FROM \"AI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI03_FEED'\n\n",
     "select": [
      [
       { "params": [ "ai_02lrv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ai_02urv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "OUT AO 2 - 4 a 20 mA", "type": "volkovlabs-form-panel", "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 } },
  {
   "title": "Tendencia AOs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "alias": "AO 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AO_PV_DATA",
     "query": "SELECT mean(\"ao_00out\") AS \"OUT 1\" FROM \"AO_PV_DATA\" WHERE \"sensor\"::tag = 'AO00'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "ao_00out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "AO00" }
     ]
    },
    {
     "alias": "AO 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AO_PV_DATA",
     "query": "SELECT  mean(\"ao_01out\") AS \"OUT 2\" FROM \"AO_PV_DATA\" WHERE \"sensor\"::tag = 'AO01' AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "ao_00out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "AO00" }
     ]
    }
   ]
  }
 ]
}