{
 "title": "Panel Chequeo Presostato",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "unidad", "label": "Unidad", "query": "bar, mbar, psi, Kg/cm2" }
  ]
 },
 "panels": [
  {
   "title": "Taller Instrumentos PRIII",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# 🧪 Panel Chequeo Presostato\n\n**Canales:** `DIa.0` `AI.0`\n"
   }
  },
  { "title": "PANEL CHEQUEO PRESOSTATO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "unidad" },
  {
   "title": "Presión Manométrica",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "raw_data",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AI_PV_DATA",
     "query": "from(bucket: \"plc_data_bucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"AI_PV_DATA\" and\r\n    r._field == \"ai_00pv\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _time: r._time,\r\n        _value: float(v: r._value)\r\n      })\r\n    )\r\n",
     "select": [
      [
       { "params": [ "ai_00pv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DI",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DI_PV_DATA",
     "query": "from(bucket: \"plc_data_bucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"AI_PV_DATA\" and\r\n    r._field == \"ai_00pv\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _time: r._time,\r\n        _value: float(v: r._value)\r\n      })\r\n    )\r\n",
     "select": [
      [
       { "params": [ "di00_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Contacto Presostato",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DI 01",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"di00_input\") FROM \"DI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DI00'\n",
     "select": [
      [
       { "params": [ "di00_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI00" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "30d" }
     ]
    }
   ]
  },
  {
   "title": "Presión Manométrica",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "bar",
     "measurement": "AI_PV_DATA",
     "select": [
      [
       { "params": [ "ai_00pv" ], "type": "field" }
      ]
     ],
     "slimit": "1"
    },
    {
     "alias": "lrv",
     "query": "SELECT last(\"ai_00lrv\") AS \"lrv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI00'"
    },
    {
     "alias": "urv",
     "query": "SELECT last(\"ai_00urv\") AS \"lrv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI00'"
    }
   ]
  },
  {
   "title": "Rango actual",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "LRV",
     "query": "SELECT last(\"ai_00lrv\") AS \"lrv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI00'"
    },
    {
     "alias": "URV",
     "query": "SELECT last(\"ai_00urv\") AS \"urv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI00'"
    }
   ]
  }
 ]
}