{
 "title": "Panel Entradas Salidas Digitales",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "selectDI", "label": "Graficar DI", "query": "DI_01,DI_02,DI_03,DI_04" },
   { "name": "selectDO", "label": "Graficar DO", "query": "DO_01,DO_02,DO_03,DO_04" }
  ]
 },
 "panels": [
  {
   "title": "Taller Instrumentos PRIII",
   "type": "text",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "# 🧪 Panel Entradas Salidas Digitales\n\n**Canales:** `DI00` `DI01` `DI02` `DI03` `DO00` `DO01` `DO02` `DO03`\n"
   }
  },
  {
   "title": "Patrón manométrico",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bar g" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "bar g",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AI_PV_DATA",
     "query": "from(bucket: \"plc_data_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AI00PV\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group()",
     "select": [
      [
       { "params": [ "ai_00pv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Patrón absoluto",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbar  a" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "mbar a",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AI_PV_DATA",
     "query": "from(bucket: \"plc_data_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ai_01pv\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group()\r\n",
     "select": [
      [
       { "params": [ "ai_01pv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Entradas digitales",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DI 01",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"di00_input\") FROM \"DI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DI00'\n",
     "select": [
      [
       { "params": [ "di00_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI00" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "30d" }
     ]
    },
    {
     "alias": "DI 02",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"di01_input\") FROM \"DI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DI01'",
     "select": [
      [
       { "params": [ "di01_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI01" }
     ]
    },
    {
     "alias": "DI 03",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"di02_input\") FROM \"DI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DI02'",
     "select": [
      [
       { "params": [ "di02_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI02" }
     ]
    },
    {
     "alias": "DI 04",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"di03_input\") FROM \"DI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DI03'",
     "select": [
      [
       { "params": [ "di03_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI03" }
     ]
    }
   ]
  },
  { "title": "Activar DO's", "type": "volkovlabs-form-panel", "gridPos": { "h": 7, "w": 3, "x": 12, "y": 4 } },
  {
   "title": "Estado de las salidas digitales",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DO 01",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"DO00_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO00'\n",
     "select": [
      [
       { "params": [ "di00_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI00" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "30d" }
     ]
    },
    {
     "alias": "DO 02",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"DO01_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO01'",
     "select": [
      [
       { "params": [ "di01_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI01" }
     ]
    },
    {
     "alias": "DO 03",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"DO02_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO02'",
     "select": [
      [
       { "params": [ "di02_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI02" }
     ]
    },
    {
     "alias": "DO 04",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"DO03_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO03'",
     "select": [
      [
       { "params": [ "di03_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI03" }
     ]
    }
   ]
  },
  {
   "title": "Tendencia DI's",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "DI_01",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AO_PV_DATA",
     "query": "SELECT mean(\"di00_input\") AS \"DI 1\" FROM \"DI_PV_DATA\" WHERE \"sensor\"::tag = 'DI00'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "ao_00out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "AO00" }
     ]
    },
    {
     "alias": "DI_02",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AO_PV_DATA",
     "query": "SELECT mean(\"di01_input\") AS \"DI 2\" FROM \"DI_PV_DATA\" WHERE \"sensor\"::tag = 'DI01'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "ao_00out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "AO00" }
     ]
    },
    {
     "alias": "DI_03",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AO_PV_DATA",
     "query": "SELECT mean(\"di02_input\") AS \"DI 3\" FROM \"DI_PV_DATA\" WHERE \"sensor\"::tag = 'DI02'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "ao_00out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "AO00" }
     ]
    },
    {
     "alias": "DI_04",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AO_PV_DATA",
     "query": "SELECT mean(\"di03_input\") AS \"DI 4\" FROM \"DI_PV_DATA\" WHERE \"sensor\"::tag = 'DI03'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "ao_00out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "AO00" }
     ]
    }
   ]
  },
  {
   "title": "Tendencia DO's",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "alias": "DO_01",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AO_PV_DATA",
     "query": "SELECT mean(\"DO00_OUT\") AS \"DO 1\" FROM \"DO_PV_DATA\" WHERE \"sensor\"::tag = 'DO00'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "ao_00out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "AO00" }
     ]
    },
    {
     "alias": "DO_02",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AO_PV_DATA",
     "query": "SELECT mean(\"DO01_OUT\") AS \"DO 2\" FROM \"DO_PV_DATA\" WHERE \"sensor\"::tag = 'DO01'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "ao_00out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "AO00" }
     ]
    },
    {
     "alias": "DO_03",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AO_PV_DATA",
     "query": "SELECT mean(\"DO02_OUT\") AS \"DO 3\" FROM \"DO_PV_DATA\" WHERE \"sensor\"::tag = 'DO02'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "ao_00out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "AO00" }
     ]
    },
    {
     "alias": "DO_04",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AO_PV_DATA",
     "query": "SELECT mean(\"DO03_OUT\") AS \"DO 4\" FROM \"DO_PV_DATA\" WHERE \"sensor\"::tag = 'DO03'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "ao_00out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "AO00" }
     ]
    }
   ]
  }
 ]
}