{
 "title": "Panel Entradas Salidas Digitales",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "selectDI", "label": "Graficar DI", "query": "DI_01,DI_02,DI_03,DI_04" },
   {
    "name": "selectDO",
    "label": "Graficar DO",
    "query": "DO_01,DO_02,DO_03,DO_04,DO_05,DO_06,DO_07,DO_08"
   }
  ]
 },
 "panels": [
  {
   "title": "Taller Instrumentos PRIII",
   "type": "text",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "# 🧪 Panel Entradas Salidas Digitales\n\n**Canales:** `DIa.0` `DIa.1` `DIa.2` `DIa.3` `DQa.0` `DQa.1` `DQa.2` `DQa.3` `DQa.4` `DQa.5` `DQa.6` `DQa.7`\n"
   }
  },
  {
   "title": "Patrón manométrico",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bar g" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "bar g",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AI_PV_DATA",
     "query": "from(bucket: \"plc_data_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AI00PV\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group()",
     "select": [
      [
       { "params": [ "ai_00pv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Patrón absoluto",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbar  a" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "mbar a",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AI_PV_DATA",
     "query": "from(bucket: \"plc_data_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ai_01pv\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group()\r\n",
     "select": [
      [
       { "params": [ "ai_01pv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SALIDAS DIGITALES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "selectDO",
   "collapsed": true,
   "panels": [
    {
     "title": "Tendencia ${selectDO}",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 9, "x": 0, "y": 5 },
     "targets": [
      {
       "alias": "DO_01",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "AO_PV_DATA",
       "query": "SELECT mean(\"DO00_OUT\") AS \"DO 1\" FROM \"DO_PV_DATA\" WHERE \"sensor\"::tag = 'DO00'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
       "select": [
        [
         { "params": [ "ao_00out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "AO00" }
       ]
      },
      {
       "alias": "DO_02",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "AO_PV_DATA",
       "query": "SELECT mean(\"DO01_OUT\") AS \"DO 2\" FROM \"DO_PV_DATA\" WHERE \"sensor\"::tag = 'DO01'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
       "select": [
        [
         { "params": [ "ao_00out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "AO00" }
       ]
      },
      {
       "alias": "DO_03",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "AO_PV_DATA",
       "query": "SELECT mean(\"DO02_OUT\") AS \"DO 3\" FROM \"DO_PV_DATA\" WHERE \"sensor\"::tag = 'DO02'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
       "select": [
        [
         { "params": [ "ao_00out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "AO00" }
       ]
      },
      {
       "alias": "DO_04",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "AO_PV_DATA",
       "query": "SELECT mean(\"DO03_OUT\") AS \"DO 4\" FROM \"DO_PV_DATA\" WHERE \"sensor\"::tag = 'DO03'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
       "select": [
        [
         { "params": [ "ao_00out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "AO00" }
       ]
      },
      {
       "alias": "DO_05",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "AO_PV_DATA",
       "query": "SELECT mean(\"DO04_OUT\") AS \"DO 5\" FROM \"DO_PV_DATA\" WHERE \"sensor\"::tag = 'DO04'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
       "select": [
        [
         { "params": [ "ao_00out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "AO00" }
       ]
      },
      {
       "alias": "DO_06",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "AO_PV_DATA",
       "query": "SELECT mean(\"DO05_OUT\") AS \"DO 6\" FROM \"DO_PV_DATA\" WHERE \"sensor\"::tag = 'DO05'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
       "select": [
        [
         { "params": [ "ao_00out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "AO00" }
       ]
      },
      {
       "alias": "DO_07",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "AO_PV_DATA",
       "query": "SELECT mean(\"DO06_OUT\") AS \"DO 7\" FROM \"DO_PV_DATA\" WHERE \"sensor\"::tag = 'DO06'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
       "select": [
        [
         { "params": [ "ao_00out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "AO00" }
       ]
      },
      {
       "alias": "DO_08",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "AO_PV_DATA",
       "query": "SELECT mean(\"DO07_OUT\") AS \"DO 8\" FROM \"DO_PV_DATA\" WHERE \"sensor\"::tag = 'DO07'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
       "select": [
        [
         { "params": [ "ao_00out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "AO00" }
       ]
      }
     ]
    },
    { "title": "Activar DO's", "type": "volkovlabs-form-panel", "gridPos": { "h": 13, "w": 5, "x": 9, "y": 5 } },
    {
     "title": "Estado de las salidas digitales",
     "type": "stat",
     "gridPos": { "h": 13, "w": 10, "x": 14, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "DO 01 24Vcc",
       "measurement": "DI_PV_DATA_TEST",
       "query": "SELECT last(\"DO00_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO00'\n",
       "select": [
        [
         { "params": [ "di00_input" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "DI00" },
        { "condition": "AND", "key": "time", "operator": ">", "value": "30d" }
       ]
      },
      {
       "alias": "DO 02 24Vcc",
       "measurement": "DI_PV_DATA_TEST",
       "query": "SELECT last(\"DO01_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO01'",
       "select": [
        [
         { "params": [ "di01_input" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "DI01" }
       ]
      },
      {
       "alias": "DO 03 110Vcc",
       "measurement": "DI_PV_DATA_TEST",
       "query": "SELECT last(\"DO02_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO02'",
       "select": [
        [
         { "params": [ "di02_input" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "DI02" }
       ]
      },
      {
       "alias": "DO 04 110Vcc",
       "measurement": "DI_PV_DATA_TEST",
       "query": "SELECT last(\"DO03_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO03'",
       "select": [
        [
         { "params": [ "di03_input" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "DI03" }
       ]
      },
      {
       "alias": "DO 05 110Vca",
       "measurement": "DI_PV_DATA_TEST",
       "query": "SELECT last(\"DO04_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO04'",
       "select": [
        [
         { "params": [ "di03_input" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "DI03" }
       ]
      },
      {
       "alias": "DO 06 110Vca",
       "measurement": "DI_PV_DATA_TEST",
       "query": "SELECT last(\"DO05_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO05'",
       "select": [
        [
         { "params": [ "di03_input" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "DI03" }
       ]
      },
      {
       "alias": "DO 07 220Vca",
       "measurement": "DI_PV_DATA_TEST",
       "query": "SELECT last(\"DO06_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO06'",
       "select": [
        [
         { "params": [ "di03_input" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "DI03" }
       ]
      },
      {
       "alias": "DO 08 220Vca",
       "measurement": "DI_PV_DATA_TEST",
       "query": "SELECT last(\"DO07_OUT\") FROM \"DO_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DO07'",
       "select": [
        [
         { "params": [ "di03_input" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "sensor::tag", "operator": "=", "value": "DI03" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "ENTRADAS DIGITALES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "selectDI" },
  {
   "title": "Tendencia DI's",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "DI_01",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AO_PV_DATA",
     "query": "SELECT mean(\"di00_input\") AS \"DI 1\" FROM \"DI_PV_DATA\" WHERE \"sensor\"::tag = 'DI00'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "ao_00out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "AO00" }
     ]
    },
    {
     "alias": "DI_02",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AO_PV_DATA",
     "query": "SELECT mean(\"di01_input\") AS \"DI 2\" FROM \"DI_PV_DATA\" WHERE \"sensor\"::tag = 'DI01'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "ao_00out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "AO00" }
     ]
    },
    {
     "alias": "DI_03",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AO_PV_DATA",
     "query": "SELECT mean(\"di02_input\") AS \"DI 3\" FROM \"DI_PV_DATA\" WHERE \"sensor\"::tag = 'DI02'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "ao_00out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "AO00" }
     ]
    },
    {
     "alias": "DI_04",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AO_PV_DATA",
     "query": "SELECT mean(\"di03_input\") AS \"DI 4\" FROM \"DI_PV_DATA\" WHERE \"sensor\"::tag = 'DI03'  AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "ao_00out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "AO00" }
     ]
    }
   ]
  },
  {
   "title": "Entradas digitales",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DI 01",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"di00_input\") FROM \"DI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DI00'\n",
     "select": [
      [
       { "params": [ "di00_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI00" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "30d" }
     ]
    },
    {
     "alias": "DI 02",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"di01_input\") FROM \"DI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DI01'",
     "select": [
      [
       { "params": [ "di01_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI01" }
     ]
    },
    {
     "alias": "DI 03",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"di02_input\") FROM \"DI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DI02'",
     "select": [
      [
       { "params": [ "di02_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI02" }
     ]
    },
    {
     "alias": "DI 04",
     "measurement": "DI_PV_DATA_TEST",
     "query": "SELECT last(\"di03_input\") FROM \"DI_PV_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'DI03'",
     "select": [
      [
       { "params": [ "di03_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor::tag", "operator": "=", "value": "DI03" }
     ]
    }
   ]
  }
 ]
}