{
 "title": "Presiones Patrónes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "unidad",
    "label": "Unidad PI g",
    "query": "bar, mbar, psi, mmH2O, Kg/cm2, kpa"
   },
   { "name": "unidadabs", "label": "Unidad PI abs", "query": "mbar a, atm" }
  ]
 },
 "panels": [
  {
   "title": "Taller Instrumentos PRIII",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# 📈 Panel de Presión Manométrica y Absoluta\n\n**Taller:** Instrumentos PRIII  \n**Canal:** `AI.0` `AI.1`  \n⏰ _Rango de visualización:_ ${__from:date:DD-MM-YYYY HH\\:mm\\:ss} al ${__to:date:DD-MM-YYYY HH\\:mm\\:ss}"
   }
  },
  { "title": "PATRÓN MANOMÉTRICO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "unidad" },
  {
   "title": "Presión Manométrica",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "bar",
     "measurement": "AI_PV_DATA",
     "query": "SELECT last(\"ai_00pv\") AS \"bar\" FROM \"AI_PV_DATA\" WHERE time > now() - 30d",
     "select": [
      [
       { "params": [ "ai_00pv" ], "type": "field" }
      ]
     ],
     "slimit": "1"
    }
   ]
  },
  {
   "title": "Presión Manométrica",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "alias": "bar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AI_PV_DATA",
     "query": "from(bucket: \"plc_data_bucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"AI_PV_DATA\" and\r\n    r._field == \"ai_00pv\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _time: r._time,\r\n        _value: float(v: r._value)\r\n      })\r\n    )\r\n",
     "select": [
      [
       { "params": [ "ai_00pv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rango actual",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "LRV",
     "query": "SELECT last(\"ai_00lrv\") AS \"lrv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI00'"
    },
    {
     "alias": "URV",
     "query": "SELECT last(\"ai_00urv\") AS \"urv\" FROM \"AI_CONFIG_DATA\" WHERE time > now() - 30d AND \"sensor\"::tag = 'AI00'"
    }
   ]
  },
  {
   "title": "AI 1 Configuración LRV y URV",
   "type": "volkovlabs-form-panel",
   "description": "Usar siempre un rango expresado en bar g, de lo contrario la conversión a otras unidades será erronea",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 }
  },
  { "title": "PATRÓN ABSOLUTO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "unidadabs" },
  {
   "title": "Presión Absoluta",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mbar a" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "mbar a",
     "measurement": "AI_PV_DATA",
     "query": "from(bucket: \"plc_data_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"AI_PV_DATA\" and\r\n    r._field == \"ai_01pv\"\r\n  )\r\n  |> limit(n:1)\r\n  ",
     "select": [
      [
       { "params": [ "ai_01pv" ], "type": "field" }
      ]
     ],
     "slimit": "1"
    }
   ]
  },
  {
   "title": "Presión Absoluta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "alias": "mbar a",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AI_PV_DATA",
     "query": "from(bucket: \"plc_data_bucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"AI_PV_DATA\" and\r\n    r._field == \"ai_01pv\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _time: r._time,\r\n        _value: float(v: r._value)\r\n      })\r\n    )\r\n",
     "select": [
      [
       { "params": [ "ai_01pv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}